root = "."
tmp_dir = "build"

[build]
  bin = "./build/go-development -config environment/env.yml"
  cmd = "go build -gcflags=all='-N -l' -o ./build/go-development ./src/cmd"
  delay = 1000
  exclude_dir = ["docker", ".vscode", "build", ".github", "docs", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go",  "html",  "tmpl",  "toml",  "tpl",  "yml"]
  kill_delay = "0s"
  log = "build-errors.log" # will be located at tmp_dir
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
