version: '3.8'

services:
    bhakti-portfolio-api-dev:
        image: bhaktibuana/bhakti-portfolio-api-dev:latest
        container_name: bhakti-portfolio-api-dev
        ports:
            - 3030:3030
        env_file:
            - ../.env.dev
        networks:
            - bhakti_portfolio_api_dev_network

networks:
    bhakti_portfolio_api_dev_network:
        name: bhakti_portfolio_api_dev_network
