version: '3.8'

services:
    bhakti-portfolio-api:
        image: bhaktibuana/bhakti-portfolio-api:latest
        container_name: bhakti-portfolio-api
        ports:
            - 3040:3040
        env_file:
            - ../.env.prod
        networks:
            - bhakti_portfolio_api_network

networks:
    bhakti_portfolio_api_network:
        name: bhakti_portfolio_api_network
